# Generated by Django 3.0.2 on 2020-02-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'allergic',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='DetailCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.Category')),
            ],
            options={
                'db_table': 'detail_category',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('name_eng', models.CharField(max_length=45)),
                ('introduction', models.CharField(max_length=500)),
                ('img_link', models.URLField(max_length=500)),
                ('desc', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'drink',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal_per_one', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sodium', models.DecimalField(decimal_places=1, max_digits=5)),
                ('saturated_fat', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sugars', models.DecimalField(decimal_places=1, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=5)),
                ('caffein', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'db_table': 'nutrition',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'size',
            },
        ),
        migrations.CreateModel(
            name='DrinkAllergic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.Allergic')),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.Drink')),
            ],
            options={
                'db_table': 'drink_allergic',
            },
        ),
        migrations.AddField(
            model_name='drink',
            name='allergic',
            field=models.ManyToManyField(through='drink.DrinkAllergic', to='drink.Allergic'),
        ),
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.Category'),
        ),
        migrations.AddField(
            model_name='drink',
            name='datail_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.DetailCategory'),
        ),
        migrations.AddField(
            model_name='drink',
            name='nutrition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.Nutrition'),
        ),
        migrations.AddField(
            model_name='drink',
            name='size',
            field=models.ManyToManyField(to='drink.Size'),
        ),
    ]
